---
- hosts: localhost
  tasks:
  - name: instala wget y certificados
    become: true
    apt:
     update-cache: yes
     pkg:
     - wget
     - ca-certificates
     state: present
  - name: agrega llave para repositorio postgress
    shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - name: agrega repositorio a las llaves
    shell: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
  - name: instala postgresql
    become: true
    apt:
     update-cache: yes
     pkg:
     - postgresql
     - postgresql-contrib
  - name: descarga comandos para bd
    shell: wget https://raw.githubusercontent.com/tuto/tenpo-test/master/scripts/bd/commands.sql
  - name: crea base de datos
    shell: sudo -u postgres createdb tenpo-api
  - name: asigna password al usuario
    shell: sed -i "1 i\ALTER USER postgres PASSWORD {{ lookup('env','DB_PASSWORD') }};" commands.sql
  - name: provisiona base de datos
    shell: sudo -u postgres psql -d tenpo-api -a -f commands.sql
  - name: habilitar conecciones remotas en postgres
    shell: archivo=$(sudo  find -O2 / -name "postgresql.conf" | head -n 1) && sudo sed -i "s/\#listen_addresses/listen_addresses = \'*\' \\#/g" $archivo
  - name:  habilitar en configuracion de postgress
    shell: archivo=$(sudo  find -O2 / -name "pg_hba.conf" | head -n 1) && echo 'host    all             all              all              md5' | sudo tee -a $archivo
  - name:  restart postgress
    shell: sudo /etc/init.d/postgresql restart